### ISSUE TITLE
Graphs need fixing

### ISSUE THREAD

**Issue by GaPhil** [jeppeb91/Benchmarking-Priority-Queues#3]
• Please run the script `badass.sh` again (I have made changes) on your machine to give correct output on the graphs

• Please see 4a0457a1fdc376dfa61694e9b9babaad76c303af for details

**Comment by GaPhil** [comment]
`Bench_marking/graphs/Insertion_comparison.png` needs fixing in commit: a86a930af132b2b15c328ef4ecbd5a4914471361

**Comment by jeppeb91** [comment]
Fixed some stuff. See how u like it now
